# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottom_ninth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
