# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:02
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

def slugify_position(apps, schema_editor):
	Batter = apps.get_model('bottom_ninth', 'Batter')
	for batter in Batter.objects.all():
		batter.position = slugify(batter.name)
		batter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bottom_ninth', '0002_batter_position'),
    ]

    operations = [
    	migrations.RunPython(slugify_position),
    ]
